### ISSUE TITLE
Feature: add referral option

### ISSUE THREAD

**Issue by 0x1d00ffff** [admazzola/deployart-web#2]
Reason: Referrals seem to be capable of driving large incentives to market for/talk about platforms. 

Idea: add a "referral percentage" option in the NFT definition interface and signed NFT packet. Default 0%. If set to a value, then this allows for an optional "referrer=0xADDRESS" param in the URL which, when specified, will send the configured % of the mint price to the referrer. 

Example: Alice defines NFT for 1 eth with a 1% referral percentage. She shares the signed packet with her followers. Bob can now go to the NFT mint interface and make a referral link which HE begins to share. When the NFT sells with his link, Alice gets 0.98 eth, Bob gets 0.01 eth, and Miners Guild gets 0.01 eth.

**Comment by ethereumdegen** [comment]
Merged in to latest release.  Thanks for suggestion

https://goerli.etherscan.io/tx/0x4e962da47016f8a714d502f008b9310c2d11e50ec6a7a602b1c8da9d15a73005
